### ISSUE TITLE
合作社（或任何SOHO团队）需要解决的几个问题

### ISSUE THREAD

**Issue by wizardforcel** [itgongren/996.coop#1]
（之前在群里说过的）

1.   商业模式（也就是财路）
2.   绩效（技术内部，非技术和技术之间）
3.   数据保真

**Comment by itgongren** [comment]
商业模式需要大家群策群力
绩效这个在合作社内部应该看淡。

**Comment by vkensou** [comment]
商业模式是公司都需要面对的问题，合作社解决不了。
绩效我想最好的办法是通过制度设计，自发的就实现多劳多得，不需要专门来考核绩效。
不过绩效考核也可以，蒙德拉贡是请第三方机构来定绩效标准然后考核的。

我想过业务部门和非业务部门如何评绩效。有一个办法是非业务部门，比如人力财务法律等部门成立独立合作社，给业务合作社提供外包服务，价格参考市场价，或者有一定业绩分成。

你说的数据保真是什么意思？

**Comment by Leo-Mu** [comment]
个人认为 issue 主“数据保真”的意思可能是档案制度或者代码话语权问题（git 仓库的权限、服务器运维的权限等）。
有一点很重要：不能养懒人！绩效考核可以用其他形式表现，最好的状态是每个人做好工作即可，不需要为别人对自己工作的看法再做工作，但是按参与分配成果是必须的！

**Comment by wizardforcel** [comment]
> 绩效这个在合作社内部应该看淡。

这你就不懂了，首先不能绝对平均，或者搞随机数，这样会破坏动力。（也不能差的太多，不过这个很容易用对数+线性变换来解决。）

这个比例满足有序就行了，也就是干的多的人绩效多，同时由于是合作社，所以大家都需要对这个规则满意。

**Comment by icevivi** [comment]
能否把这三个问题分开讨论？

我现在比较关注收入的问题，在收入得到保障的情况下，其他问题大家达成共识了，毕竟只是内部问题，可能还相对好办。如果没有源源不断的收入保障，大家交的股本金很快就没有了，又不希望资本投资，资金容易断链。

如果生存成了问题，其他的也没有基础了。

软件研发我认为先前投入时间是比较长的，从开始启动到有收入需要一定的周期。
接定制开发、外包，可能好一点。但这类也很有可能会为了生存，接受不合理的开发时限，还是可能会形成加班严重的问题。若坚持不加班，也有可能因为竞争者996，压低价格，合作社在市场竞争上未必有利。

**Comment by vkensou** [comment]
> 能否把这三个问题分开讨论？
> 
> 我现在比较关注收入的问题，在收入得到保障的情况下，其他问题大家达成共识了，毕竟只是内部问题，可能还相对好办。如果没有源源不断的收入保障，大家交的股本金很快就没有了，又不希望资本投资，资金容易断链。
> 
> 如果生存成了问题，其他的也没有基础了。
> 
> 软件研发我认为先前投入时间是比较长的，从开始启动到有收入需要一定的周期。
> 接定制开发、外包，可能好一点。但这类也很有可能会为了生存，接受不合理的开发时限，还是可能会形成加班严重的问题。若坚持不加班，也有可能因为竞争者996，压低价格，合作社在市场竞争上未必有利。

商业模式问题合作社无法解决，毕竟是要真金白银在市场上拼杀的。
只不过合作社有个风险共担的优势。
如果合作社只有996才能生存下去，那只能说这个行业竞争太激烈，或者自己提供的服务附加值太低。
实在不行只能996的话那也比给资本家996好啊，起码是给自己干。

**Comment by wizardforcel** [comment]
> 
> 
> 能否把这三个问题分开讨论？
> 
> 我现在比较关注收入的问题，在收入得到保障的情况下，其他问题大家达成共识了，毕竟只是内部问题，可能还相对好办。如果没有源源不断的收入保障，大家交的股本金很快就没有了，又不希望资本投资，资金容易断链。
> 
> 如果生存成了问题，其他的也没有基础了。
> 
> 软件研发我认为先前投入时间是比较长的，从开始启动到有收入需要一定的周期。
> 接定制开发、外包，可能好一点。但这类也很有可能会为了生存，接受不合理的开发时限，还是可能会形成加班严重的问题。若坚持不加班，也有可能因为竞争者996，压低价格，合作社在市场竞争上未必有利。

这个需要参考[现有的远程团队](https://github.com/greatghoul/remote-working#teams)，他们没有融资，甚至有些没有注册公司，但也活了下来。

所以咱们这个项目，做大了就是合作社，做小了就是远程团队。如果这么多团队都成功了的话，咱们也有很大机率成功啊。

所以不要怕麻烦，向他们借鉴，你不主动哪来的故事。

**Comment by icevivi** [comment]
> > 能否把这三个问题分开讨论？
> > 我现在比较关注收入的问题，在收入得到保障的情况下，其他问题大家达成共识了，毕竟只是内部问题，可能还相对好办。如果没有源源不断的收入保障，大家交的股本金很快就没有了，又不希望资本投资，资金容易断链。
> > 如果生存成了问题，其他的也没有基础了。
> > 软件研发我认为先前投入时间是比较长的，从开始启动到有收入需要一定的周期。
> > 接定制开发、外包，可能好一点。但这类也很有可能会为了生存，接受不合理的开发时限，还是可能会形成加班严重的问题。若坚持不加班，也有可能因为竞争者996，压低价格，合作社在市场竞争上未必有利。
> 
> 这个需要参考[现有的远程团队](https://github.com/greatghoul/remote-working#teams)，他们没有融资，甚至有些没有注册公司，但也活了下来。
> 
> 所以咱们这个项目，做大了就是合作社，做小了就是远程团队。如果这么多团队都成功了的话，咱们也有很大机率成功啊。
> 
> 所以不要怕麻烦，向他们借鉴，你不主动哪来的故事。

没有怕麻烦，怕麻烦也不来讨论了。
我倾向于，互相熟悉的人先组成小团队，有自己的产品和想法，小团队内先形成合作社的模式。
如果几个小团队有共同的产品目标，他们可以合并成为更大的合作社。
如果一开始就是大团队，大家是各自做自己有兴趣的呢？还是一起做个大的产品呢？这个问题在团队成立之后也还是要讨论的吧？那不如先讨论讨论。

**Comment by icevivi** [comment]
> > 能否把这三个问题分开讨论？
> > 我现在比较关注收入的问题，在收入得到保障的情况下，其他问题大家达成共识了，毕竟只是内部问题，可能还相对好办。如果没有源源不断的收入保障，大家交的股本金很快就没有了，又不希望资本投资，资金容易断链。
> > 如果生存成了问题，其他的也没有基础了。
> > 软件研发我认为先前投入时间是比较长的，从开始启动到有收入需要一定的周期。
> > 接定制开发、外包，可能好一点。但这类也很有可能会为了生存，接受不合理的开发时限，还是可能会形成加班严重的问题。若坚持不加班，也有可能因为竞争者996，压低价格，合作社在市场竞争上未必有利。
> 
> 商业模式问题合作社无法解决，毕竟是要真金白银在市场上拼杀的。
> 只不过合作社有个风险共担的优势。
> 如果合作社只有996才能生存下去，那只能说这个行业竞争太激烈，或者自己提供的服务附加值太低。
> 实在不行只能996的话那也比给资本家996好啊，起码是给自己干。

假设以平均出资为一年平均年薪。发工资以一年平均薪酬发工资，原理上一年内资金发工资就发完了，还未考虑费用支出的问题。就算大家暂时以一年平均薪酬的一半发工资，也只能坚持两年。
虽然共同劳动、共担风险的目标是实现了，可是最终的目标（成立合作社并长远发展下去）若实现不了，最终还是大家都回去打工了。
在市场经济的环境下，还是应该考虑怎么让合作社能生存下去。当然最基本的原则不能放弃，比如不要996。

**Comment by icevivi** [comment]
>> 蒙德拉贡为融资需要和提高合作社的科技水平，1959年、1974年先后成立了合作社性质的Caja Laboral劳动银行与Ikerlan技术研究中心。

我觉得他们是有源源不断的资金来源的。他们自己开银行，资金从哪来我就不知道是从外部来还是直接从内部来的。但这一定程度上，可以减轻资金压力。

**Comment by vkensou** [comment]
> > > 能否把这三个问题分开讨论？
> > > 我现在比较关注收入的问题，在收入得到保障的情况下，其他问题大家达成共识了，毕竟只是内部问题，可能还相对好办。如果没有源源不断的收入保障，大家交的股本金很快就没有了，又不希望资本投资，资金容易断链。
> > > 如果生存成了问题，其他的也没有基础了。
> > > 软件研发我认为先前投入时间是比较长的，从开始启动到有收入需要一定的周期。
> > > 接定制开发、外包，可能好一点。但这类也很有可能会为了生存，接受不合理的开发时限，还是可能会形成加班严重的问题。若坚持不加班，也有可能因为竞争者996，压低价格，合作社在市场竞争上未必有利。
> > 
> > 
> > 商业模式问题合作社无法解决，毕竟是要真金白银在市场上拼杀的。
> > 只不过合作社有个风险共担的优势。
> > 如果合作社只有996才能生存下去，那只能说这个行业竞争太激烈，或者自己提供的服务附加值太低。
> > 实在不行只能996的话那也比给资本家996好啊，起码是给自己干。
> 
> 假设以平均出资为一年平均年薪。发工资以一年平均薪酬发工资，原理上一年内资金发工资就发完了，还未考虑费用支出的问题。就算大家暂时以一年平均薪酬的一半发工资，也只能坚持两年。
> 虽然共同劳动、共担风险的目标是实现了，可是最终的目标（成立合作社并长远发展下去）若实现不了，最终还是大家都回去打工了。
> 在市场经济的环境下，还是应该考虑怎么让合作社能生存下去。当然最基本的原则不能放弃，比如不要996。

可以多投钱啊，超过一年收入的部分作为公司债务。刚创业没有收入的时候就不领工资，交个社保就够了。
