### ISSUE TITLE
讨论分红的处理机制

### ISSUE THREAD

**Issue by vkensou** [itgongren/996.coop#2]
蒙德拉贡合作社的经验是在职期间分红不可提取，离职/退休/去世才可以提取。
我也认为分红随意提取不好培养社员的长期意识。
我个人认为可以最多每三年提取一次。
欢迎大家讨论。

**Comment by itgongren** [comment]
我认为合作社企业应该不分红。

**Comment by vkensou** [comment]
> 我认为合作社企业应该不分红。

红利/利润来自承受的风险，大家出资承受风险，却不能得到利润，不可能有人接受的。

**Comment by Leo-Mu** [comment]
@itgongren 看到了您在几条 issue 下的回应，作为发起者，您是很相当有魄力有实干精神的，当然理想主义情怀大概也是您做这件事的动机之一，但请不要太过理想主义，我也是一个理想主义者，但是纵观历史，我深知这种平均主义的理想，这种敌视资本、敌视资本主义分配方式和市场经济的观点是无法带来我们所希望的进步的。

**Comment by itgongren** [comment]
> @itgongren 看到了您在几条 issue 下的回应，作为发起者，您是很相当有魄力有实干精神的，当然理想主义情怀大概也是您做这件事的动机之一，但请不要太过理想主义，我也是一个理想主义者，但是纵观历史，我深知这种平均主义的理想，这种敌视资本、敌视资本主义分配方式和市场经济的观点是无法带来我们所希望的进步的。

很多公司是从来不分红的。比如中国的股份公司。比如乔布斯时代的苹果。股东可以通过股票升值获得收益，通过出卖股份变现。如果我们允许分红，难免回到资本主义按资本分配的老路上去。

**Comment by vkensou** [comment]
> > @itgongren 看到了您在几条 issue 下的回应，作为发起者，您是很相当有魄力有实干精神的，当然理想主义情怀大概也是您做这件事的动机之一，但请不要太过理想主义，我也是一个理想主义者，但是纵观历史，我深知这种平均主义的理想，这种敌视资本、敌视资本主义分配方式和市场经济的观点是无法带来我们所希望的进步的。
> 
> 很多公司是从来不分红的。比如中国的股份公司。比如乔布斯时代的苹果。股东可以通过股票升值获得收益，通过出卖股份变现。如果我们允许分红，难免回到资本主义按资本分配的老路上去。

那么股票卖出价如何确定？买入价是一年年收入，卖出价按净资产算？如果有人进入然后干一两年就走，那就是公司资产的流失了。如果有人家里需要用钱了，那他只能卖出股票，卖出以后是自动离职还是能继续呆着？

**Comment by icevivi** [comment]
蒙德拉贡合作社的制度能否有个完整的可参考的文本？
否则只是讨论局部，看不到整体，不好讨论。
另外自己一点小想法：IT业者和工人的情况可能不太一样。在一个工厂内，可能工人的技术要求和难度都差不多。但IT技术有难度很高的，有难度一般的。如何通过报酬反应出他们的价值差异？

**Comment by vkensou** [comment]
> 蒙德拉贡合作社的制度能否有个完整的可参考的文本？
> 否则只是讨论局部，看不到整体，不好讨论。
> 另外自己一点小想法：IT业者和工人的情况可能不太一样。在一个工厂内，可能工人的技术要求和难度都差不多。但IT技术有难度很高的，有难度一般的。如何通过报酬反应出他们的价值差异？

[蒙德拉贡的介绍](https://baike.baidu.com/item/%E8%92%99%E5%BE%B7%E6%8B%89%E8%B4%A1%E8%81%94%E5%90%88%E5%85%AC%E5%8F%B8)

报酬还是要参考市场价。不过要做一定的平衡，让低收入者收入高一点，高收入者低一点。

**Comment by icevivi** [comment]
> > 蒙德拉贡合作社的制度能否有个完整的可参考的文本？
> > 否则只是讨论局部，看不到整体，不好讨论。
> > 另外自己一点小想法：IT业者和工人的情况可能不太一样。在一个工厂内，可能工人的技术要求和难度都差不多。但IT技术有难度很高的，有难度一般的。如何通过报酬反应出他们的价值差异？

> 报酬还是要参考市场价。不过要做一定的平衡，让低收入者收入高一点，高收入者低一点。

我理解的蒙德拉贡不是不分红，只是分红的金额先记入”个人资本账户“，平时不允许提出，在退出或退休或去世时才提出。我觉得这样还可以。但我比较同意比如每三年提出一次（不全部提出）的想法，或个人有特殊情况，比如生病或希望买房等急需资金的情况，应该还是允许先提出一部分。

**Comment by vkensou** [comment]
> > > 蒙德拉贡合作社的制度能否有个完整的可参考的文本？
> > > 否则只是讨论局部，看不到整体，不好讨论。
> > > 另外自己一点小想法：IT业者和工人的情况可能不太一样。在一个工厂内，可能工人的技术要求和难度都差不多。但IT技术有难度很高的，有难度一般的。如何通过报酬反应出他们的价值差异？
> 
> > 报酬还是要参考市场价。不过要做一定的平衡，让低收入者收入高一点，高收入者低一点。
> 
> 我理解的蒙德拉贡不是不分红，只是分红的金额先记入”个人资本账户“，平时不允许提出，在退出或退休或去世时才提出。我觉得这样还可以。但我比较同意比如每三年提出一次（不全部提出）的想法，或个人有特殊情况，比如生病或希望买房等急需资金的情况，应该还是允许先提出一部分。

就是不知道银行是否能开这种无法提取的储蓄账户。

**Comment by icevivi** [comment]
> 就是不知道银行是否能开这种无法提取的储蓄账户。

"个人资本账户”应该只是指财务为每个人建立一个账簿，记录每个人“应该分红“的金额。并不需要为每个人在银行开设账号。提出时，转账肯定还是从公有的公司账户转出给个人。
