### ISSUE TITLE
讨论入股退股的机制

### ISSUE THREAD

**Issue by vkensou** [itgongren/996.coop#3]
我个人观点：

每股价格为当地的1年平均收入。
最多分三年缴清。相当于这三年每个月扣除月工资的三分之一，这样应该不会影响刚进入社会的员工的生活。
如果是分期缴清，那么期间的投票权、分红也应该是根据实缴的比例来计算，比如只缴了1/3，那么投票权也只有1/3。
新员工应有3-6个月的考察期（试用期），通过考察期后要有1-2周的入股培训，学习如何做股东。通过试用期而不愿入股的员工也要尊重其意愿。
股份禁止转让，离职/去世由公司强制回购。退休可以保留部分股份（分红达到当地年平均收入为宜）。
股份回购价格为 当地年平均收入与公司每股流动现金的最小值。

**Comment by vkensou** [comment]
关于股份回购价格也可以改为当地年平均收入与公司每股净资产的最小值
我想的是不能因为有人离职把公司的流动现金给掏空了

**Comment by Leo-Mu** [comment]
呃，这里有一个问题哈：

>通过试用期而不愿入股的员工也要尊重其意愿。

如果这一条成立，那么必然出现有股权者和无股权者两个阶级，实际上产生雇佣与被雇佣关系，本质上与现行制度毫无区别，一定时间的演化后，严重的剥削仍不可避免。

**Comment by vkensou** [comment]
> 呃，这里有一个问题哈：
> 
> > 通过试用期而不愿入股的员工也要尊重其意愿。
> 
> 如果这一条成立，那么必然出现有股权者和无股权者两个阶级，实际上产生雇佣与被雇佣关系，本质上与现行制度毫无区别，一定时间的演化后，严重的剥削仍不可避免。

想进入随时可以进入。但是人家不想入股总不能把人踢了把。

**Comment by icevivi** [comment]
注册有限责任公司，是可以以无形资产入股的。
所以，合作社是否也需要考虑一下，如果员工有个人的知识产权，希望以无形资产方式投入到合作社，要怎么处理？

**Comment by vkensou** [comment]
> 注册有限责任公司，是可以以无形资产入股的。
> 所以，合作社是否也需要考虑一下，如果员工有个人的知识产权，希望以无形资产方式投入到合作社，要怎么处理？

具体入股形式可以合作社股东会讨论决定。
我个人认为这种情况可以先算个价格，如果这个知识产权或者专利跟一年收入差不太多，可以多退少补。价值比较大或者难以计算价格的，可以仍然按普通方式入股，然后公司按市场价每年付给使用费。
