### ISSUE TITLE
关于来自外部的股权投资

### ISSUE THREAD

**Issue by vkensou** [itgongren/996.coop#6]
应该可以接受其他合作社的股权投资，但是股权比例需要认真考虑。我认为一个解决办法是转化为两合作社的合并。

我想了下针对非合作社的投资
合作社可以采用AB股的形式接受非合作社的股权投资。合作社社员持有B类股，买卖价格为一年收入，有N票投票权；外部投资者持有A类股，买卖价格是市场价或净资产价，有1票投票权。但是这个有缺点就是单个社员的投票权太少，可能会被外部投资者各个击破。

不知道大家怎么看？

**Comment by vkensou** [comment]
要不就只能完全拒绝来自非合作社的股权投资。初期只能避免烧钱的项目。
烧钱的项目只能等到合作社发展壮大之后，由合作社内部裂变或者合作社投资合作社了。

**Comment by icevivi** [comment]
暂时我觉得还不会有“两个合作社”合作或合并的情况。
我觉得外部资金，以借款方式比较好。
避免烧钱的项目，狠抓现金流。
有了现金流入，积累起来，就可摆脱外部资本的控制。

**Comment by vkensou** [comment]
> 暂时我觉得还不会有“两个合作社”合作或合并的情况。
> 我觉得外部资金，以借款方式比较好。
> 避免烧钱的项目，狠抓现金流。
> 有了现金流入，积累起来，就可摆脱外部资本的控制。

没有抵押物是借不到钱的

**Comment by vkensou** [comment]
> 暂时我觉得还不会有“两个合作社”合作或合并的情况。
> 我觉得外部资金，以借款方式比较好。
> 避免烧钱的项目，狠抓现金流。
> 有了现金流入，积累起来，就可摆脱外部资本的控制。

银行的低息贷款，私企是基本借不到的。能借到的利率都很高。

**Comment by icevivi** [comment]
> > 暂时我觉得还不会有“两个合作社”合作或合并的情况。
> > 我觉得外部资金，以借款方式比较好。
> > 避免烧钱的项目，狠抓现金流。
> > 有了现金流入，积累起来，就可摆脱外部资本的控制。
> 
> 银行的低息贷款，私企是基本借不到的。能借到的利率都很高。

如果不想接受外部资本的投资，就只能借。银行贷款利率也有上限，也不会高到特别离谱的地步。
而且象武汉，对高新技术企业有50%的贴息，这方面有政策优惠可以充分利用起来。
虽然贷款总是难的，但也不是完全没有办法。如果企业发展好，贷款机会会提高。初创企业可能是会比较难些，但创业初期，有个人投入的资金，一时没有产生现金流，也不适合贷款。要贷款也肯定是产品开始有现金流，追加投入就可产生效益，也还得起利息的情况下才会去贷款。

**Comment by icevivi** [comment]
> > 暂时我觉得还不会有“两个合作社”合作或合并的情况。
> > 我觉得外部资金，以借款方式比较好。
> > 避免烧钱的项目，狠抓现金流。
> > 有了现金流入，积累起来，就可摆脱外部资本的控制。
> 
> 没有抵押物是借不到钱的

无形资产也可以做为抵押物进行贷款的。这个各个地方或各个银行的政策不太一样，有的松些有的紧些，但这个是银行允许开展的业务，只是各个银行支持的程度不一样。

**Comment by icevivi** [comment]
另外，象高新技术企业，武汉有政府补助，研发补助，这些都可以考虑去争取。这类政策各地不一样。
